  /api/update:
    get:
      summary: Get all updates
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of updates
    post:
      summary: Create a new update
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                productID:
                  type: string
      responses:
        '201':
          description: Update created

  /api/update/{id}:
    get:
      summary: Get a single update by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Update details
    put:
      summary: Update an update
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                status:
                  type: string
                  enum: [IN_PROGRESS, SHIPPED, DEPRECATED]
                version:
                  type: string
      responses:
        '200':
          description: Update modified
    delete:
      summary: Delete an update
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Update deleted

  /api/updatepoint:
    get:
      summary: Get all update points
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of update points
    post:
      summary: Create an update point
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                updateID:
                  type: string
      responses:
        '201':
          description: Update point created

  /api/updatepoint/{id}:
    get:
      summary: Get a single update point by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Update point details
    put:
      summary: Update an update point
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Update point modified
    delete:
      summary: Delete an update point
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Update point deleted
  components:
    securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
        